Azure.Web/Controllers/BlobDemoController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Azure.Web.Helper;
using Microsoft.WindowsAzure.Storage.Blob;

namespace Azure.Web.Controllers
{
    public class BlobDemoController : Controller
    {

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        private string ContainerName = "tst2";
        private CloudBlobContainer ContainerReference
        {
            get { return BlobHelper.GetContainerReference(ContainerName); }
        }

        public ActionResult Index()
        {
            var model = BlobHelper.ListAllBlob(ContainerReference);
            return View(model);
        }

        public ActionResult Add()
        {
            //var products = db.Products.Include(p => p.ProductCategory).Include(p => p.ProductModel);
            return View();
        }

        [HttpPost]
        public ActionResult Upload()
        {
            if (Request.Files.Count > 0)
            {
                HttpPostedFileBase file = Request.Files[0];

                if (file != null && file.ContentLength > 0)
                {
                    BlobHelper.UploadFile(ContainerReference, file);
                }
            }
            return RedirectToAction("Index");
        }

        
    }
}

Azure.Web/Views/BlobDemo/Add.cshtml
@model dynamic

@{
    ViewBag.Title = "title";
}

<h2>title</h2>


@using (Html.BeginForm("Upload", "BlobDemo", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <input type="file" name="file" />
    <input type="submit" name="Submit" id="Submit" value="Upload" />
}

Azure.Web/Views/BlobDemo/Index.cshtml
@using Microsoft.WindowsAzure.Storage.Blob
@model IEnumerable<IListBlobItem>

@{
    ViewBag.Title = "title";
}

<h2>Blob Demo</h2>

@Html.ActionLink("Add File", "Add", "BlobDemo")

<br />

@foreach (IListBlobItem item in Model)
{
    <img src="@item.Uri" />
    <br />
}